### PR TITLE
Added version 1.3.0

### LINKED ISSUE #2: 1.3.0 dlls
I have a pr to make kOS compatible with 1.3.0 but it needs libraries here.

### PR DESCRIPTION
**Pull request by pipakin**
- Created dlls with https://github.com/dbent/AssemblyPlacholder
- Fixes #2 
- Needed for KOS update to 1.3.0.

### CODE REVIEW

**Comment by Dunbaratu** [comment]
@pipakin - This still isn't allowing Travis to succeed at compiling.

I've gotten this set of errors when I just tested a Travis build using the new 1.3 DLLs this PR provided:

```
	Module/kOSVesselModule.cs(50,33): error CS0115: 'kOSVesselModule.OnAwake()': no suitable method found to override

	Module/kOSVesselModule.cs(71,33): error CS0115: 'kOSVesselModule.OnStart()': no suitable method found to override

	Module/kOSVesselModule.cs(85,33): error CS0115: 'kOSVesselModule.OnLoad(ConfigNode)': no suitable method found to override
```

I'm not sure how you're supposed to use AssemblyPlaceholder to create the stub DLLs but something doesn't seem right about how they got made if Travis is throwing those errors.  @hvacengi was the one who set this all up the first time and I'm trying to get up to speed on it.
